<?php

$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();

$categoryCollection = $objectManager->get('\Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');

$categoryHelper = $objectManager->get('\Magento\Catalog\Helper\Category');

$categories = $categoryHelper->getStoreCategories();

$_outputhelper = $this->helper('Magento\Catalog\Helper\Output');

$_imgHtml   = '';

?>
<div class="homepage-categories-wrapper">
    <div class="container">
        <div class="row">
            <?php
            foreach ($categories as $category) :

                $cat_data = $category->getData();

            ?>

                <?php
                $category_id = $cat_data['entity_id'];
                $_productCollection = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\Collection');
                $_productCollection->addCategoriesFilter(['in' => [$category_id]]);
                $_productCollection->addAttributeToSelect('*');
                $_productCollection->load();

                $_helper = $this->helper('Magento\Catalog\Helper\Output');
                $viewMode = 'list';
                $image = 'category_page_list';
                $showDescription = true;
                $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
                $pos = $block->getPositioned();

                if (count($_productCollection) > 0) :
                ?>
                    <div class="home-category">
                        <a href="<?php echo $this->getUrl($cat_data['request_path']); ?>" title="<?php echo $category->getName(); ?>">
                            <span>
                                <?php echo $category->getName(); ?>
                            </span>
                        </a>

                        <div class="products">
                            <?php $iterator = 1; ?>
                            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                            <?php foreach ($_productCollection as $_product) : ?>
                                <?= ($iterator++ == 1) ? '<div class="product">' : '</div><div class="product">' ?>
                                <div class="product-actions">
                                    <a href="#" data-post='<?php echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product) ?>' class="action towishlist" data-action="add-to-wishlist">
                                        <i class="fas fa-heart fa-lg" aria-hidden="true"></i>
                                    </a>
                                    <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)) : ?>
                                        <a href="<?php echo $_compareUrl ?>" class="action compare">
                                            <i class="fas fa-chart-bar fa-lg" aria-hidden="true"></i>
                                        </a>
                                    <?php endif; ?>
                                </div>
                                <div class="product-info" data-container="product-grid">
                                    <?php
                                    $productImage = $block->getImage($_product, $image);
                                    if ($pos != null) {
                                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                            . 'top:' . $productImage->getHeight() . 'px;"';
                                    }
                                    ?>

                                    <a href="<?= $_product->getProductUrl() ?>" class="product-photo" tabindex="-1" style="background:url('<?= $productImage->getImageUrl() ?>') center;background-size:cover;">
                                        <?= $productImage->toHtml() ?>
                                    </a>
                                    <div class="product-details">
                                        <?php
                                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                        ?>
                                        <a class="product-link" href="<?= $_product->getProductUrl() ?>">
                                            <?= $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                        </a>

                                        <?= $block->getProductPrice($_product) ?>
                                    </div>

                                </div>
                                <?= ($iterator == count($_productCollection) + 1) ? '</div>' : '' ?>
                            <?php endforeach; ?>
                        </div>
                    </div>
            <?php endif;
            endforeach;
            ?>
        </div>
    </div>
</div>